import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <ul>
            <li><a href="/">prerendered - no leak</a></li>
            <li><a href="/leak">prerendered - leak</a></li>
            <li><a href="/dynamic">dynamic (ok)</a></li>
            <li><a href="/dynamic?leak=1">dynamic (leak)</a></li>
            <li><a href="/client">client - no leak</a></li>
            <li><a href="/api-node">API (ok)</a></li>
            <li><a href="/api-node?leak=1">API (leak)</a></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
